### ISSUE TITLE
add glue CoMID HWVer -> Implementation ID

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-psa-endorsements#19]
When the supply chain entity responsible for provisioning certification related data is unable to link it to an Implementation ID, we need a way to make that association (HWVer->ImplID) via an assertion from some other supply chain actor (e.g., the device manufacturer).  This means two things:
1. we need to have the cert data identified by HWVer as an alternative to ImplID (in case the matching ImplID is not known);
2. we need to have a glue CoMID that endorses a specific HWVer as associated to an ImplID.

**Comment by yogeshbdeshpande** [comment]
Just be clear on point 2:  A CoMID representing a HW Claim of HW Version, as represented in Atomic Model, should suffice, isn't it?
This way, if a Certification CoMID  is provisioned by a Certification Authority with HW Version, a Verifier can still look up into its Database to identify CoMID matching HW Version and then fetching the associated Implementation ID of the platform RoT?

**Comment by thomas-fossati** [comment]
Yes!

Case 1: certifier and manufacturer are separate endorsements/ref-value providers:
* manufacturer => {ImplID: RefValue(PRoT), ..., **Endorsement(HwVer)**, Identity(IAK1), ...}
* certifier => {HwVer: Endorsement(Cert)}

Case 2: certifier and manufacturer are collapsed into one (e.g., manufacturer proxies the certifier):
* manufacturer => {ImplID: RefValue(PRoT), ..., Endorsement(Cert), Identity(IAK1), ...}

**Comment by yogeshbdeshpande** [comment]
Case 1: Certifier and Manufacturer provision the endorsement/ref-values indepedently.

Case 2, I would prefer to clarify that Certifier issues the certification to the manufacturer which can provision  endorsements and ref-values together!

**Comment by thomas-fossati** [comment]
> Case 2, I would prefer to clarify that Certifier issues the certification to the manufacturer which can provision endorsements and ref-values together!

Strictly speaking the certification is not issued to the manufacturer.  The certifier creates the cert record and the manufacturer proxies it to the verifier.

**Comment by yogeshbdeshpande** [comment]
Agree and Nice Pictures!
